# CD de la branche Dev
name: Continuous Delivery - Dev

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "groupe1-dev"
          heroku_email: "gatien.boquet@gmail.com"
          healthcheck: "https://groupe1-dev.herokuapp.com"
          usedocker: true
          dontuseforce: 0

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - uses: edge/simple-slack-notify@master
      with:
        status: ${{ job.status }}
        success_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) Deploy completed successfully'
        failure_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) Deploy failed'
        cancelled_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) Deploy was cancelled'
        fields: |
          [{ "title": "Repository", "value": "${env.GITHUB_REPOSITORY}", "short": true },
          { "title": "Branch", "value": "${env.GITHUB_REF_NAME}", "short": true }]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}